
<option @if($selected == "fa-500px" ) {!! 'selected' !!} @endif value="fa-500px ">500px </option>
<option @if($selected == "fa-adjust" ) {!! 'selected' !!} @endif value="fa-adjust ">adjust </option>
<option @if($selected == "fa-adn" ) {!! 'selected' !!} @endif value="fa-adn ">adn </option>
<option @if($selected == "fa-align-center" ) {!! 'selected' !!} @endif value="fa-align-center ">align-center </option>
<option @if($selected == "fa-align-justify" ) {!! 'selected' !!} @endif value="fa-align-justify ">align-justify </option>
<option @if($selected == "fa-align-left" ) {!! 'selected' !!} @endif value="fa-align-left ">align-left </option>
<option @if($selected == "fa-align-right" ) {!! 'selected' !!} @endif value="fa-align-right ">align-right </option>
<option @if($selected == "fa-amazon" ) {!! 'selected' !!} @endif value="fa-amazon ">amazon </option>
<option @if($selected == "fa-ambulance" ) {!! 'selected' !!} @endif value="fa-ambulance ">ambulance </option>
<option @if($selected == "fa-anchor" ) {!! 'selected' !!} @endif value="fa-anchor ">anchor </option>
<option @if($selected == "fa-android" ) {!! 'selected' !!} @endif value="fa-android ">android </option>
<option @if($selected == "fa-angellist" ) {!! 'selected' !!} @endif value="fa-angellist ">angellist </option>
<option @if($selected == "fa-angle-double-down" ) {!! 'selected' !!} @endif value="fa-angle-double-down ">angle-double-down </option>
<option @if($selected == "fa-angle-double-left" ) {!! 'selected' !!} @endif value="fa-angle-double-left ">angle-double-left </option>
<option @if($selected == "fa-angle-double-right" ) {!! 'selected' !!} @endif value="fa-angle-double-right ">angle-double-right </option>
<option @if($selected == "fa-angle-double-up" ) {!! 'selected' !!} @endif value="fa-angle-double-up ">angle-double-up </option>
<option @if($selected == "fa-angle-down" ) {!! 'selected' !!} @endif value="fa-angle-down ">angle-down </option>
<option @if($selected == "fa-angle-left" ) {!! 'selected' !!} @endif value="fa-angle-left ">angle-left </option>
<option @if($selected == "fa-angle-right" ) {!! 'selected' !!} @endif value="fa-angle-right ">angle-right </option>
<option @if($selected == "fa-angle-up" ) {!! 'selected' !!} @endif value="fa-angle-up ">angle-up </option>
<option @if($selected == "fa-apple" ) {!! 'selected' !!} @endif value="fa-apple ">apple </option>
<option @if($selected == "fa-archive" ) {!! 'selected' !!} @endif value="fa-archive ">archive </option>
<option @if($selected == "fa-area-chart" ) {!! 'selected' !!} @endif value="fa-area-chart ">area-chart </option>
<option @if($selected == "fa-arrow-circle-down" ) {!! 'selected' !!} @endif value="fa-arrow-circle-down ">arrow-circle-down </option>
<option @if($selected == "fa-arrow-circle-left" ) {!! 'selected' !!} @endif value="fa-arrow-circle-left ">arrow-circle-left </option>
<option @if($selected == "fa-arrow-circle-o-down" ) {!! 'selected' !!} @endif value="fa-arrow-circle-o-down ">arrow-circle-o-down </option>
<option @if($selected == "fa-arrow-circle-o-left" ) {!! 'selected' !!} @endif value="fa-arrow-circle-o-left ">arrow-circle-o-left </option>
<option @if($selected == "fa-arrow-circle-o-right" ) {!! 'selected' !!} @endif value="fa-arrow-circle-o-right ">arrow-circle-o-right </option>
<option @if($selected == "fa-arrow-circle-o-up" ) {!! 'selected' !!} @endif value="fa-arrow-circle-o-up ">arrow-circle-o-up </option>
<option @if($selected == "fa-arrow-circle-right" ) {!! 'selected' !!} @endif value="fa-arrow-circle-right ">arrow-circle-right </option>
<option @if($selected == "fa-arrow-circle-up" ) {!! 'selected' !!} @endif value="fa-arrow-circle-up ">arrow-circle-up </option>
<option @if($selected == "fa-arrow-down" ) {!! 'selected' !!} @endif value="fa-arrow-down ">arrow-down </option>
<option @if($selected == "fa-arrow-left" ) {!! 'selected' !!} @endif value="fa-arrow-left ">arrow-left </option>
<option @if($selected == "fa-arrow-right" ) {!! 'selected' !!} @endif value="fa-arrow-right ">arrow-right </option>
<option @if($selected == "fa-arrow-up" ) {!! 'selected' !!} @endif value="fa-arrow-up ">arrow-up </option>
<option @if($selected == "fa-arrows" ) {!! 'selected' !!} @endif value="fa-arrows ">arrows </option>
<option @if($selected == "fa-arrows-alt" ) {!! 'selected' !!} @endif value="fa-arrows-alt ">arrows-alt </option>
<option @if($selected == "fa-arrows-h" ) {!! 'selected' !!} @endif value="fa-arrows-h ">arrows-h </option>
<option @if($selected == "fa-arrows-v" ) {!! 'selected' !!} @endif value="fa-arrows-v ">arrows-v </option>
<option @if($selected == "fa-asterisk" ) {!! 'selected' !!} @endif value="fa-asterisk ">asterisk </option>
<option @if($selected == "fa-at" ) {!! 'selected' !!} @endif value="fa-at ">at </option>
<option @if($selected == "fa-automobileEvent" ) {!! 'selected' !!} @endif value="fa-automobileEvent ">automobileEvent </option>
<option @if($selected == "fa-backward" ) {!! 'selected' !!} @endif value="fa-backward ">backward </option>
<option @if($selected == "fa-balance-scale" ) {!! 'selected' !!} @endif value="fa-balance-scale ">balance-scale </option>
<option @if($selected == "fa-ban" ) {!! 'selected' !!} @endif value="fa-ban ">ban </option>
<option @if($selected == "fa-bankEvent" ) {!! 'selected' !!} @endif value="fa-bankEvent ">bankEvent </option>
<option @if($selected == "fa-bar-chart" ) {!! 'selected' !!} @endif value="fa-bar-chart ">bar-chart </option>
<option @if($selected == "fa-bar-chart-oEvent" ) {!! 'selected' !!} @endif value="fa-bar-chart-oEvent ">bar-chart-oEvent </option>
<option @if($selected == "fa-barcode" ) {!! 'selected' !!} @endif value="fa-barcode ">barcode </option>
<option @if($selected == "fa-bars" ) {!! 'selected' !!} @endif value="fa-bars ">bars </option>
<option @if($selected == "fa-battery-0Event" ) {!! 'selected' !!} @endif value="fa-battery-0Event ">battery-0Event </option>
<option @if($selected == "fa-battery-1Event" ) {!! 'selected' !!} @endif value="fa-battery-1Event ">battery-1Event </option>
<option @if($selected == "fa-battery-2Event" ) {!! 'selected' !!} @endif value="fa-battery-2Event ">battery-2Event </option>
<option @if($selected == "fa-battery-3Event" ) {!! 'selected' !!} @endif value="fa-battery-3Event ">battery-3Event </option>
<option @if($selected == "fa-battery-4Event" ) {!! 'selected' !!} @endif value="fa-battery-4Event ">battery-4Event </option>
<option @if($selected == "fa-battery-empty" ) {!! 'selected' !!} @endif value="fa-battery-empty ">battery-empty </option>
<option @if($selected == "fa-battery-full" ) {!! 'selected' !!} @endif value="fa-battery-full ">battery-full </option>
<option @if($selected == "fa-battery-half" ) {!! 'selected' !!} @endif value="fa-battery-half ">battery-half </option>
<option @if($selected == "fa-battery-quarter" ) {!! 'selected' !!} @endif value="fa-battery-quarter ">battery-quarter </option>
<option @if($selected == "fa-battery-three-quarters" ) {!! 'selected' !!} @endif value="fa-battery-three-quarters ">battery-three-quarters </option>
<option @if($selected == "fa-bed" ) {!! 'selected' !!} @endif value="fa-bed ">bed </option>
<option @if($selected == "fa-beer" ) {!! 'selected' !!} @endif value="fa-beer ">beer </option>
<option @if($selected == "fa-behance" ) {!! 'selected' !!} @endif value="fa-behance ">behance </option>
<option @if($selected == "fa-behance-square" ) {!! 'selected' !!} @endif value="fa-behance-square ">behance-square </option>
<option @if($selected == "fa-bell" ) {!! 'selected' !!} @endif value="fa-bell ">bell </option>
<option @if($selected == "fa-bell-o" ) {!! 'selected' !!} @endif value="fa-bell-o ">bell-o </option>
<option @if($selected == "fa-bell-slash" ) {!! 'selected' !!} @endif value="fa-bell-slash ">bell-slash </option>
<option @if($selected == "fa-bell-slash-o" ) {!! 'selected' !!} @endif value="fa-bell-slash-o ">bell-slash-o </option>
<option @if($selected == "fa-bicycle" ) {!! 'selected' !!} @endif value="fa-bicycle ">bicycle </option>
<option @if($selected == "fa-binoculars" ) {!! 'selected' !!} @endif value="fa-binoculars ">binoculars </option>
<option @if($selected == "fa-birthday-cake" ) {!! 'selected' !!} @endif value="fa-birthday-cake ">birthday-cake </option>
<option @if($selected == "fa-bitbucket" ) {!! 'selected' !!} @endif value="fa-bitbucket ">bitbucket </option>
<option @if($selected == "fa-bitbucket-square" ) {!! 'selected' !!} @endif value="fa-bitbucket-square ">bitbucket-square </option>
<option @if($selected == "fa-bitcoinEvent" ) {!! 'selected' !!} @endif value="fa-bitcoinEvent ">bitcoinEvent </option>
<option @if($selected == "fa-black-tie" ) {!! 'selected' !!} @endif value="fa-black-tie ">black-tie </option>
<option @if($selected == "fa-bluetooth" ) {!! 'selected' !!} @endif value="fa-bluetooth ">bluetooth </option>
<option @if($selected == "fa-bluetooth-b" ) {!! 'selected' !!} @endif value="fa-bluetooth-b ">bluetooth-b </option>
<option @if($selected == "fa-bold" ) {!! 'selected' !!} @endif value="fa-bold ">bold </option>
<option @if($selected == "fa-bolt" ) {!! 'selected' !!} @endif value="fa-bolt ">bolt </option>
<option @if($selected == "fa-bomb" ) {!! 'selected' !!} @endif value="fa-bomb ">bomb </option>
<option @if($selected == "fa-book" ) {!! 'selected' !!} @endif value="fa-book ">book </option>
<option @if($selected == "fa-bookmark" ) {!! 'selected' !!} @endif value="fa-bookmark ">bookmark </option>
<option @if($selected == "fa-bookmark-o" ) {!! 'selected' !!} @endif value="fa-bookmark-o ">bookmark-o </option>
<option @if($selected == "fa-briefcase" ) {!! 'selected' !!} @endif value="fa-briefcase ">briefcase </option>
<option @if($selected == "fa-btc" ) {!! 'selected' !!} @endif value="fa-btc ">btc </option>
<option @if($selected == "fa-bug" ) {!! 'selected' !!} @endif value="fa-bug ">bug </option>
<option @if($selected == "fa-building" ) {!! 'selected' !!} @endif value="fa-building ">building </option>
<option @if($selected == "fa-building-o" ) {!! 'selected' !!} @endif value="fa-building-o ">building-o </option>
<option @if($selected == "fa-bullhorn" ) {!! 'selected' !!} @endif value="fa-bullhorn ">bullhorn </option>
<option @if($selected == "fa-bullseye" ) {!! 'selected' !!} @endif value="fa-bullseye ">bullseye </option>
<option @if($selected == "fa-bus" ) {!! 'selected' !!} @endif value="fa-bus ">bus </option>
<option @if($selected == "fa-buysellads" ) {!! 'selected' !!} @endif value="fa-buysellads ">buysellads </option>
<option @if($selected == "fa-cabEvent" ) {!! 'selected' !!} @endif value="fa-cabEvent ">cabEvent </option>
<option @if($selected == "fa-calculator" ) {!! 'selected' !!} @endif value="fa-calculator ">calculator </option>
<option @if($selected == "fa-calendar" ) {!! 'selected' !!} @endif value="fa-calendar ">calendar </option>
<option @if($selected == "fa-calendar-check-o" ) {!! 'selected' !!} @endif value="fa-calendar-check-o ">calendar-check-o </option>
<option @if($selected == "fa-calendar-minus-o" ) {!! 'selected' !!} @endif value="fa-calendar-minus-o ">calendar-minus-o </option>
<option @if($selected == "fa-calendar-o" ) {!! 'selected' !!} @endif value="fa-calendar-o ">calendar-o </option>
<option @if($selected == "fa-calendar-plus-o" ) {!! 'selected' !!} @endif value="fa-calendar-plus-o ">calendar-plus-o </option>
<option @if($selected == "fa-calendar-times-o" ) {!! 'selected' !!} @endif value="fa-calendar-times-o ">calendar-times-o </option>
<option @if($selected == "fa-camera" ) {!! 'selected' !!} @endif value="fa-camera ">camera </option>
<option @if($selected == "fa-camera-retro" ) {!! 'selected' !!} @endif value="fa-camera-retro ">camera-retro </option>
<option @if($selected == "fa-car" ) {!! 'selected' !!} @endif value="fa-car ">car </option>
<option @if($selected == "fa-caret-down" ) {!! 'selected' !!} @endif value="fa-caret-down ">caret-down </option>
<option @if($selected == "fa-caret-left" ) {!! 'selected' !!} @endif value="fa-caret-left ">caret-left </option>
<option @if($selected == "fa-caret-right" ) {!! 'selected' !!} @endif value="fa-caret-right ">caret-right </option>
<option @if($selected == "fa-caret-square-o-down" ) {!! 'selected' !!} @endif value="fa-caret-square-o-down ">caret-square-o-down </option>
<option @if($selected == "fa-caret-square-o-left" ) {!! 'selected' !!} @endif value="fa-caret-square-o-left ">caret-square-o-left </option>
<option @if($selected == "fa-caret-square-o-right" ) {!! 'selected' !!} @endif value="fa-caret-square-o-right ">caret-square-o-right </option>
<option @if($selected == "fa-caret-square-o-up" ) {!! 'selected' !!} @endif value="fa-caret-square-o-up ">caret-square-o-up </option>
<option @if($selected == "fa-caret-up" ) {!! 'selected' !!} @endif value="fa-caret-up ">caret-up </option>
<option @if($selected == "fa-cart-arrow-down" ) {!! 'selected' !!} @endif value="fa-cart-arrow-down ">cart-arrow-down </option>
<option @if($selected == "fa-cart-plus" ) {!! 'selected' !!} @endif value="fa-cart-plus ">cart-plus </option>
<option @if($selected == "fa-cc" ) {!! 'selected' !!} @endif value="fa-cc ">cc </option>
<option @if($selected == "fa-cc-amex" ) {!! 'selected' !!} @endif value="fa-cc-amex ">cc-amex </option>
<option @if($selected == "fa-cc-diners-club" ) {!! 'selected' !!} @endif value="fa-cc-diners-club ">cc-diners-club </option>
<option @if($selected == "fa-cc-discover" ) {!! 'selected' !!} @endif value="fa-cc-discover ">cc-discover </option>
<option @if($selected == "fa-cc-jcb" ) {!! 'selected' !!} @endif value="fa-cc-jcb ">cc-jcb </option>
<option @if($selected == "fa-cc-mastercard" ) {!! 'selected' !!} @endif value="fa-cc-mastercard ">cc-mastercard </option>
<option @if($selected == "fa-cc-paypal" ) {!! 'selected' !!} @endif value="fa-cc-paypal ">cc-paypal </option>
<option @if($selected == "fa-cc-stripe" ) {!! 'selected' !!} @endif value="fa-cc-stripe ">cc-stripe </option>
<option @if($selected == "fa-cc-visa" ) {!! 'selected' !!} @endif value="fa-cc-visa ">cc-visa </option>
<option @if($selected == "fa-certificate" ) {!! 'selected' !!} @endif value="fa-certificate ">certificate </option>
<option @if($selected == "fa-chainEvent" ) {!! 'selected' !!} @endif value="fa-chainEvent ">chainEvent </option>
<option @if($selected == "fa-chain-broken" ) {!! 'selected' !!} @endif value="fa-chain-broken ">chain-broken </option>
<option @if($selected == "fa-check" ) {!! 'selected' !!} @endif value="fa-check ">check </option>
<option @if($selected == "fa-check-circle" ) {!! 'selected' !!} @endif value="fa-check-circle ">check-circle </option>
<option @if($selected == "fa-check-circle-o" ) {!! 'selected' !!} @endif value="fa-check-circle-o ">check-circle-o </option>
<option @if($selected == "fa-check-square" ) {!! 'selected' !!} @endif value="fa-check-square ">check-square </option>
<option @if($selected == "fa-check-square-o" ) {!! 'selected' !!} @endif value="fa-check-square-o ">check-square-o </option>
<option @if($selected == "fa-chevron-circle-down" ) {!! 'selected' !!} @endif value="fa-chevron-circle-down ">chevron-circle-down </option>
<option @if($selected == "fa-chevron-circle-left" ) {!! 'selected' !!} @endif value="fa-chevron-circle-left ">chevron-circle-left </option>
<option @if($selected == "fa-chevron-circle-right" ) {!! 'selected' !!} @endif value="fa-chevron-circle-right ">chevron-circle-right </option>
<option @if($selected == "fa-chevron-circle-up" ) {!! 'selected' !!} @endif value="fa-chevron-circle-up ">chevron-circle-up </option>
<option @if($selected == "fa-chevron-down" ) {!! 'selected' !!} @endif value="fa-chevron-down ">chevron-down </option>
<option @if($selected == "fa-chevron-left" ) {!! 'selected' !!} @endif value="fa-chevron-left ">chevron-left </option>
<option @if($selected == "fa-chevron-right" ) {!! 'selected' !!} @endif value="fa-chevron-right ">chevron-right </option>
<option @if($selected == "fa-chevron-up" ) {!! 'selected' !!} @endif value="fa-chevron-up ">chevron-up </option>
<option @if($selected == "fa-child" ) {!! 'selected' !!} @endif value="fa-child ">child </option>
<option @if($selected == "fa-chrome" ) {!! 'selected' !!} @endif value="fa-chrome ">chrome </option>
<option @if($selected == "fa-circle" ) {!! 'selected' !!} @endif value="fa-circle ">circle </option>
<option @if($selected == "fa-circle-o" ) {!! 'selected' !!} @endif value="fa-circle-o ">circle-o </option>
<option @if($selected == "fa-circle-o-notch" ) {!! 'selected' !!} @endif value="fa-circle-o-notch ">circle-o-notch </option>
<option @if($selected == "fa-circle-thin" ) {!! 'selected' !!} @endif value="fa-circle-thin ">circle-thin </option>
<option @if($selected == "fa-clipboard" ) {!! 'selected' !!} @endif value="fa-clipboard ">clipboard </option>
<option @if($selected == "fa-clock-o" ) {!! 'selected' !!} @endif value="fa-clock-o ">clock-o </option>
<option @if($selected == "fa-clone" ) {!! 'selected' !!} @endif value="fa-clone ">clone </option>
<option @if($selected == "fa-closeEvent" ) {!! 'selected' !!} @endif value="fa-closeEvent ">closeEvent </option>
<option @if($selected == "fa-cloud" ) {!! 'selected' !!} @endif value="fa-cloud ">cloud </option>
<option @if($selected == "fa-cloud-download" ) {!! 'selected' !!} @endif value="fa-cloud-download ">cloud-download </option>
<option @if($selected == "fa-cloud-upload" ) {!! 'selected' !!} @endif value="fa-cloud-upload ">cloud-upload </option>
<option @if($selected == "fa-cnyEvent" ) {!! 'selected' !!} @endif value="fa-cnyEvent ">cnyEvent </option>
<option @if($selected == "fa-code" ) {!! 'selected' !!} @endif value="fa-code ">code </option>
<option @if($selected == "fa-code-fork" ) {!! 'selected' !!} @endif value="fa-code-fork ">code-fork </option>
<option @if($selected == "fa-codepen" ) {!! 'selected' !!} @endif value="fa-codepen ">codepen </option>
<option @if($selected == "fa-codiepie" ) {!! 'selected' !!} @endif value="fa-codiepie ">codiepie </option>
<option @if($selected == "fa-coffee" ) {!! 'selected' !!} @endif value="fa-coffee ">coffee </option>
<option @if($selected == "fa-cog" ) {!! 'selected' !!} @endif value="fa-cog ">cog </option>
<option @if($selected == "fa-cogs" ) {!! 'selected' !!} @endif value="fa-cogs ">cogs </option>
<option @if($selected == "fa-columns" ) {!! 'selected' !!} @endif value="fa-columns ">columns </option>
<option @if($selected == "fa-comment" ) {!! 'selected' !!} @endif value="fa-comment ">comment </option>
<option @if($selected == "fa-comment-o" ) {!! 'selected' !!} @endif value="fa-comment-o ">comment-o </option>
<option @if($selected == "fa-commenting" ) {!! 'selected' !!} @endif value="fa-commenting ">commenting </option>
<option @if($selected == "fa-commenting-o" ) {!! 'selected' !!} @endif value="fa-commenting-o ">commenting-o </option>
<option @if($selected == "fa-comments" ) {!! 'selected' !!} @endif value="fa-comments ">comments </option>
<option @if($selected == "fa-comments-o" ) {!! 'selected' !!} @endif value="fa-comments-o ">comments-o </option>
<option @if($selected == "fa-compass" ) {!! 'selected' !!} @endif value="fa-compass ">compass </option>
<option @if($selected == "fa-compress" ) {!! 'selected' !!} @endif value="fa-compress ">compress </option>
<option @if($selected == "fa-connectdevelop" ) {!! 'selected' !!} @endif value="fa-connectdevelop ">connectdevelop </option>
<option @if($selected == "fa-contao" ) {!! 'selected' !!} @endif value="fa-contao ">contao </option>
<option @if($selected == "fa-copyEvent" ) {!! 'selected' !!} @endif value="fa-copyEvent ">copyEvent </option>
<option @if($selected == "fa-copyright" ) {!! 'selected' !!} @endif value="fa-copyright ">copyright </option>
<option @if($selected == "fa-creative-commons" ) {!! 'selected' !!} @endif value="fa-creative-commons ">creative-commons </option>
<option @if($selected == "fa-credit-card" ) {!! 'selected' !!} @endif value="fa-credit-card ">credit-card </option>
<option @if($selected == "fa-credit-card-alt" ) {!! 'selected' !!} @endif value="fa-credit-card-alt ">credit-card-alt </option>
<option @if($selected == "fa-crop" ) {!! 'selected' !!} @endif value="fa-crop ">crop </option>
<option @if($selected == "fa-crosshairs" ) {!! 'selected' !!} @endif value="fa-crosshairs ">crosshairs </option>
<option @if($selected == "fa-css3" ) {!! 'selected' !!} @endif value="fa-css3 ">css3 </option>
<option @if($selected == "fa-cube" ) {!! 'selected' !!} @endif value="fa-cube ">cube </option>
<option @if($selected == "fa-cubes" ) {!! 'selected' !!} @endif value="fa-cubes ">cubes </option>
<option @if($selected == "fa-cutEvent" ) {!! 'selected' !!} @endif value="fa-cutEvent ">cutEvent </option>
<option @if($selected == "fa-cutlery" ) {!! 'selected' !!} @endif value="fa-cutlery ">cutlery </option>
<option @if($selected == "fa-dashboardEvent" ) {!! 'selected' !!} @endif value="fa-dashboardEvent ">dashboardEvent </option>
<option @if($selected == "fa-dashcube" ) {!! 'selected' !!} @endif value="fa-dashcube ">dashcube </option>
<option @if($selected == "fa-database" ) {!! 'selected' !!} @endif value="fa-database ">database </option>
<option @if($selected == "fa-dedentEvent" ) {!! 'selected' !!} @endif value="fa-dedentEvent ">dedentEvent </option>
<option @if($selected == "fa-delicious" ) {!! 'selected' !!} @endif value="fa-delicious ">delicious </option>
<option @if($selected == "fa-desktop" ) {!! 'selected' !!} @endif value="fa-desktop ">desktop </option>
<option @if($selected == "fa-deviantart" ) {!! 'selected' !!} @endif value="fa-deviantart ">deviantart </option>
<option @if($selected == "fa-diamond" ) {!! 'selected' !!} @endif value="fa-diamond ">diamond </option>
<option @if($selected == "fa-digg" ) {!! 'selected' !!} @endif value="fa-digg ">digg </option>
<option @if($selected == "fa-dollarEvent" ) {!! 'selected' !!} @endif value="fa-dollarEvent ">dollarEvent </option>
<option @if($selected == "fa-dot-circle-o" ) {!! 'selected' !!} @endif value="fa-dot-circle-o ">dot-circle-o </option>
<option @if($selected == "fa-download" ) {!! 'selected' !!} @endif value="fa-download ">download </option>
<option @if($selected == "fa-dribbble" ) {!! 'selected' !!} @endif value="fa-dribbble ">dribbble </option>
<option @if($selected == "fa-dropbox" ) {!! 'selected' !!} @endif value="fa-dropbox ">dropbox </option>
<option @if($selected == "fa-drupal" ) {!! 'selected' !!} @endif value="fa-drupal ">drupal </option>
<option @if($selected == "fa-edge" ) {!! 'selected' !!} @endif value="fa-edge ">edge </option>
<option @if($selected == "fa-editEvent" ) {!! 'selected' !!} @endif value="fa-editEvent ">editEvent </option>
<option @if($selected == "fa-eject" ) {!! 'selected' !!} @endif value="fa-eject ">eject </option>
<option @if($selected == "fa-ellipsis-h" ) {!! 'selected' !!} @endif value="fa-ellipsis-h ">ellipsis-h </option>
<option @if($selected == "fa-ellipsis-v" ) {!! 'selected' !!} @endif value="fa-ellipsis-v ">ellipsis-v </option>
<option @if($selected == "fa-empire" ) {!! 'selected' !!} @endif value="fa-empire ">empire </option>
<option @if($selected == "fa-envelope" ) {!! 'selected' !!} @endif value="fa-envelope ">envelope </option>
<option @if($selected == "fa-envelope-o" ) {!! 'selected' !!} @endif value="fa-envelope-o ">envelope-o </option>
<option @if($selected == "fa-envelope-square" ) {!! 'selected' !!} @endif value="fa-envelope-square ">envelope-square </option>
<option @if($selected == "fa-eraser" ) {!! 'selected' !!} @endif value="fa-eraser ">eraser </option>
<option @if($selected == "fa-eur" ) {!! 'selected' !!} @endif value="fa-eur ">eur </option>
<option @if($selected == "fa-euroEvent" ) {!! 'selected' !!} @endif value="fa-euroEvent ">euroEvent </option>
<option @if($selected == "fa-exchange" ) {!! 'selected' !!} @endif value="fa-exchange ">exchange </option>
<option @if($selected == "fa-exclamation" ) {!! 'selected' !!} @endif value="fa-exclamation ">exclamation </option>
<option @if($selected == "fa-exclamation-circle" ) {!! 'selected' !!} @endif value="fa-exclamation-circle ">exclamation-circle </option>
<option @if($selected == "fa-exclamation-triangle" ) {!! 'selected' !!} @endif value="fa-exclamation-triangle ">exclamation-triangle </option>
<option @if($selected == "fa-expand" ) {!! 'selected' !!} @endif value="fa-expand ">expand </option>
<option @if($selected == "fa-expeditedssl" ) {!! 'selected' !!} @endif value="fa-expeditedssl ">expeditedssl </option>
<option @if($selected == "fa-external-link" ) {!! 'selected' !!} @endif value="fa-external-link ">external-link </option>
<option @if($selected == "fa-external-link-square" ) {!! 'selected' !!} @endif value="fa-external-link-square ">external-link-square </option>
<option @if($selected == "fa-eye" ) {!! 'selected' !!} @endif value="fa-eye ">eye </option>
<option @if($selected == "fa-eye-slash" ) {!! 'selected' !!} @endif value="fa-eye-slash ">eye-slash </option>
<option @if($selected == "fa-eyedropper" ) {!! 'selected' !!} @endif value="fa-eyedropper ">eyedropper </option>
<option @if($selected == "fa-facebook" ) {!! 'selected' !!} @endif value="fa-facebook ">facebook </option>
<option @if($selected == "fa-facebook-fEvent" ) {!! 'selected' !!} @endif value="fa-facebook-fEvent ">facebook-fEvent </option>
<option @if($selected == "fa-facebook-official" ) {!! 'selected' !!} @endif value="fa-facebook-official ">facebook-official </option>
<option @if($selected == "fa-facebook-square" ) {!! 'selected' !!} @endif value="fa-facebook-square ">facebook-square </option>
<option @if($selected == "fa-fast-backward" ) {!! 'selected' !!} @endif value="fa-fast-backward ">fast-backward </option>
<option @if($selected == "fa-fast-forward" ) {!! 'selected' !!} @endif value="fa-fast-forward ">fast-forward </option>
<option @if($selected == "fa-fax" ) {!! 'selected' !!} @endif value="fa-fax ">fax </option>
<option @if($selected == "fa-feedEvent" ) {!! 'selected' !!} @endif value="fa-feedEvent ">feedEvent </option>
<option @if($selected == "fa-female" ) {!! 'selected' !!} @endif value="fa-female ">female </option>
<option @if($selected == "fa-fighter-jet" ) {!! 'selected' !!} @endif value="fa-fighter-jet ">fighter-jet </option>
<option @if($selected == "fa-file" ) {!! 'selected' !!} @endif value="fa-file ">file </option>
<option @if($selected == "fa-file-archive-o" ) {!! 'selected' !!} @endif value="fa-file-archive-o ">file-archive-o </option>
<option @if($selected == "fa-file-audio-o" ) {!! 'selected' !!} @endif value="fa-file-audio-o ">file-audio-o </option>
<option @if($selected == "fa-file-code-o" ) {!! 'selected' !!} @endif value="fa-file-code-o ">file-code-o </option>
<option @if($selected == "fa-file-excel-o" ) {!! 'selected' !!} @endif value="fa-file-excel-o ">file-excel-o </option>
<option @if($selected == "fa-file-image-o" ) {!! 'selected' !!} @endif value="fa-file-image-o ">file-image-o </option>
<option @if($selected == "fa-file-movie-oEvent" ) {!! 'selected' !!} @endif value="fa-file-movie-oEvent ">file-movie-oEvent </option>
<option @if($selected == "fa-file-o" ) {!! 'selected' !!} @endif value="fa-file-o ">file-o </option>
<option @if($selected == "fa-file-pdf-o" ) {!! 'selected' !!} @endif value="fa-file-pdf-o ">file-pdf-o </option>
<option @if($selected == "fa-file-photo-oEvent" ) {!! 'selected' !!} @endif value="fa-file-photo-oEvent ">file-photo-oEvent </option>
<option @if($selected == "fa-file-picture-oEvent" ) {!! 'selected' !!} @endif value="fa-file-picture-oEvent ">file-picture-oEvent </option>
<option @if($selected == "fa-file-powerpoint-o" ) {!! 'selected' !!} @endif value="fa-file-powerpoint-o ">file-powerpoint-o </option>
<option @if($selected == "fa-file-sound-oEvent" ) {!! 'selected' !!} @endif value="fa-file-sound-oEvent ">file-sound-oEvent </option>
<option @if($selected == "fa-file-text" ) {!! 'selected' !!} @endif value="fa-file-text ">file-text </option>
<option @if($selected == "fa-file-text-o" ) {!! 'selected' !!} @endif value="fa-file-text-o ">file-text-o </option>
<option @if($selected == "fa-file-video-o" ) {!! 'selected' !!} @endif value="fa-file-video-o ">file-video-o </option>
<option @if($selected == "fa-file-word-o" ) {!! 'selected' !!} @endif value="fa-file-word-o ">file-word-o </option>
<option @if($selected == "fa-file-zip-oEvent" ) {!! 'selected' !!} @endif value="fa-file-zip-oEvent ">file-zip-oEvent </option>
<option @if($selected == "fa-files-o" ) {!! 'selected' !!} @endif value="fa-files-o ">files-o </option>
<option @if($selected == "fa-film" ) {!! 'selected' !!} @endif value="fa-film ">film </option>
<option @if($selected == "fa-filter" ) {!! 'selected' !!} @endif value="fa-filter ">filter </option>
<option @if($selected == "fa-fire" ) {!! 'selected' !!} @endif value="fa-fire ">fire </option>
<option @if($selected == "fa-fire-extinguisher" ) {!! 'selected' !!} @endif value="fa-fire-extinguisher ">fire-extinguisher </option>
<option @if($selected == "fa-firefox" ) {!! 'selected' !!} @endif value="fa-firefox ">firefox </option>
<option @if($selected == "fa-flag" ) {!! 'selected' !!} @endif value="fa-flag ">flag </option>
<option @if($selected == "fa-flag-checkered" ) {!! 'selected' !!} @endif value="fa-flag-checkered ">flag-checkered </option>
<option @if($selected == "fa-flag-o" ) {!! 'selected' !!} @endif value="fa-flag-o ">flag-o </option>
<option @if($selected == "fa-flashEvent" ) {!! 'selected' !!} @endif value="fa-flashEvent ">flashEvent </option>
<option @if($selected == "fa-flask" ) {!! 'selected' !!} @endif value="fa-flask ">flask </option>
<option @if($selected == "fa-flickr" ) {!! 'selected' !!} @endif value="fa-flickr ">flickr </option>
<option @if($selected == "fa-floppy-o" ) {!! 'selected' !!} @endif value="fa-floppy-o ">floppy-o </option>
<option @if($selected == "fa-folder" ) {!! 'selected' !!} @endif value="fa-folder ">folder </option>
<option @if($selected == "fa-folder-o" ) {!! 'selected' !!} @endif value="fa-folder-o ">folder-o </option>
<option @if($selected == "fa-folder-open" ) {!! 'selected' !!} @endif value="fa-folder-open ">folder-open </option>
<option @if($selected == "fa-folder-open-o" ) {!! 'selected' !!} @endif value="fa-folder-open-o ">folder-open-o </option>
<option @if($selected == "fa-font" ) {!! 'selected' !!} @endif value="fa-font ">font </option>
<option @if($selected == "fa-fonticons" ) {!! 'selected' !!} @endif value="fa-fonticons ">fonticons </option>
<option @if($selected == "fa-fort-awesome" ) {!! 'selected' !!} @endif value="fa-fort-awesome ">fort-awesome </option>
<option @if($selected == "fa-forumbee" ) {!! 'selected' !!} @endif value="fa-forumbee ">forumbee </option>
<option @if($selected == "fa-forward" ) {!! 'selected' !!} @endif value="fa-forward ">forward </option>
<option @if($selected == "fa-foursquare" ) {!! 'selected' !!} @endif value="fa-foursquare ">foursquare </option>
<option @if($selected == "fa-frown-o" ) {!! 'selected' !!} @endif value="fa-frown-o ">frown-o </option>
<option @if($selected == "fa-futbol-o" ) {!! 'selected' !!} @endif value="fa-futbol-o ">futbol-o </option>
<option @if($selected == "fa-gamepad" ) {!! 'selected' !!} @endif value="fa-gamepad ">gamepad </option>
<option @if($selected == "fa-gavel" ) {!! 'selected' !!} @endif value="fa-gavel ">gavel </option>
<option @if($selected == "fa-gbp" ) {!! 'selected' !!} @endif value="fa-gbp ">gbp </option>
<option @if($selected == "fa-geEvent" ) {!! 'selected' !!} @endif value="fa-geEvent ">geEvent </option>
<option @if($selected == "fa-gearEvent" ) {!! 'selected' !!} @endif value="fa-gearEvent ">gearEvent </option>
<option @if($selected == "fa-gearsEvent" ) {!! 'selected' !!} @endif value="fa-gearsEvent ">gearsEvent </option>
<option @if($selected == "fa-genderless" ) {!! 'selected' !!} @endif value="fa-genderless ">genderless </option>
<option @if($selected == "fa-get-pocket" ) {!! 'selected' !!} @endif value="fa-get-pocket ">get-pocket </option>
<option @if($selected == "fa-gg" ) {!! 'selected' !!} @endif value="fa-gg ">gg </option>
<option @if($selected == "fa-gg-circle" ) {!! 'selected' !!} @endif value="fa-gg-circle ">gg-circle </option>
<option @if($selected == "fa-gift" ) {!! 'selected' !!} @endif value="fa-gift ">gift </option>
<option @if($selected == "fa-git" ) {!! 'selected' !!} @endif value="fa-git ">git </option>
<option @if($selected == "fa-git-square" ) {!! 'selected' !!} @endif value="fa-git-square ">git-square </option>
<option @if($selected == "fa-github" ) {!! 'selected' !!} @endif value="fa-github ">github </option>
<option @if($selected == "fa-github-alt" ) {!! 'selected' !!} @endif value="fa-github-alt ">github-alt </option>
<option @if($selected == "fa-github-square" ) {!! 'selected' !!} @endif value="fa-github-square ">github-square </option>
<option @if($selected == "fa-gittipEvent" ) {!! 'selected' !!} @endif value="fa-gittipEvent ">gittipEvent </option>
<option @if($selected == "fa-glass" ) {!! 'selected' !!} @endif value="fa-glass ">glass </option>
<option @if($selected == "fa-globe" ) {!! 'selected' !!} @endif value="fa-globe ">globe </option>
<option @if($selected == "fa-google" ) {!! 'selected' !!} @endif value="fa-google ">google </option>
<option @if($selected == "fa-google-plus" ) {!! 'selected' !!} @endif value="fa-google-plus ">google-plus </option>
<option @if($selected == "fa-google-plus-square" ) {!! 'selected' !!} @endif value="fa-google-plus-square ">google-plus-square </option>
<option @if($selected == "fa-google-wallet" ) {!! 'selected' !!} @endif value="fa-google-wallet ">google-wallet </option>
<option @if($selected == "fa-graduation-cap" ) {!! 'selected' !!} @endif value="fa-graduation-cap ">graduation-cap </option>
<option @if($selected == "fa-gratipay" ) {!! 'selected' !!} @endif value="fa-gratipay ">gratipay </option>
<option @if($selected == "fa-groupEvent" ) {!! 'selected' !!} @endif value="fa-groupEvent ">groupEvent </option>
<option @if($selected == "fa-h-square" ) {!! 'selected' !!} @endif value="fa-h-square ">h-square </option>
<option @if($selected == "fa-hacker-news" ) {!! 'selected' !!} @endif value="fa-hacker-news ">hacker-news </option>
<option @if($selected == "fa-hand-grab-oEvent" ) {!! 'selected' !!} @endif value="fa-hand-grab-oEvent ">hand-grab-oEvent </option>
<option @if($selected == "fa-hand-lizard-o" ) {!! 'selected' !!} @endif value="fa-hand-lizard-o ">hand-lizard-o </option>
<option @if($selected == "fa-hand-o-down" ) {!! 'selected' !!} @endif value="fa-hand-o-down ">hand-o-down </option>
<option @if($selected == "fa-hand-o-left" ) {!! 'selected' !!} @endif value="fa-hand-o-left ">hand-o-left </option>
<option @if($selected == "fa-hand-o-right" ) {!! 'selected' !!} @endif value="fa-hand-o-right ">hand-o-right </option>
<option @if($selected == "fa-hand-o-up" ) {!! 'selected' !!} @endif value="fa-hand-o-up ">hand-o-up </option>
<option @if($selected == "fa-hand-paper-o" ) {!! 'selected' !!} @endif value="fa-hand-paper-o ">hand-paper-o </option>
<option @if($selected == "fa-hand-peace-o" ) {!! 'selected' !!} @endif value="fa-hand-peace-o ">hand-peace-o </option>
<option @if($selected == "fa-hand-pointer-o" ) {!! 'selected' !!} @endif value="fa-hand-pointer-o ">hand-pointer-o </option>
<option @if($selected == "fa-hand-rock-o" ) {!! 'selected' !!} @endif value="fa-hand-rock-o ">hand-rock-o </option>
<option @if($selected == "fa-hand-scissors-o" ) {!! 'selected' !!} @endif value="fa-hand-scissors-o ">hand-scissors-o </option>
<option @if($selected == "fa-hand-spock-o" ) {!! 'selected' !!} @endif value="fa-hand-spock-o ">hand-spock-o </option>
<option @if($selected == "fa-hand-stop-oEvent" ) {!! 'selected' !!} @endif value="fa-hand-stop-oEvent ">hand-stop-oEvent </option>
<option @if($selected == "fa-hashtag" ) {!! 'selected' !!} @endif value="fa-hashtag ">hashtag </option>
<option @if($selected == "fa-hdd-o" ) {!! 'selected' !!} @endif value="fa-hdd-o ">hdd-o </option>
<option @if($selected == "fa-header" ) {!! 'selected' !!} @endif value="fa-header ">header </option>
<option @if($selected == "fa-headphones" ) {!! 'selected' !!} @endif value="fa-headphones ">headphones </option>
<option @if($selected == "fa-heart" ) {!! 'selected' !!} @endif value="fa-heart ">heart </option>
<option @if($selected == "fa-heart-o" ) {!! 'selected' !!} @endif value="fa-heart-o ">heart-o </option>
<option @if($selected == "fa-heartbeat" ) {!! 'selected' !!} @endif value="fa-heartbeat ">heartbeat </option>
<option @if($selected == "fa-history" ) {!! 'selected' !!} @endif value="fa-history ">history </option>
<option @if($selected == "fa-home" ) {!! 'selected' !!} @endif value="fa-home ">home </option>
<option @if($selected == "fa-hospital-o" ) {!! 'selected' !!} @endif value="fa-hospital-o ">hospital-o </option>
<option @if($selected == "fa-hotelEvent" ) {!! 'selected' !!} @endif value="fa-hotelEvent ">hotelEvent </option>
<option @if($selected == "fa-hourglass" ) {!! 'selected' !!} @endif value="fa-hourglass ">hourglass </option>
<option @if($selected == "fa-hourglass-1Event" ) {!! 'selected' !!} @endif value="fa-hourglass-1Event ">hourglass-1Event </option>
<option @if($selected == "fa-hourglass-2Event" ) {!! 'selected' !!} @endif value="fa-hourglass-2Event ">hourglass-2Event </option>
<option @if($selected == "fa-hourglass-3Event" ) {!! 'selected' !!} @endif value="fa-hourglass-3Event ">hourglass-3Event </option>
<option @if($selected == "fa-hourglass-end" ) {!! 'selected' !!} @endif value="fa-hourglass-end ">hourglass-end </option>
<option @if($selected == "fa-hourglass-half" ) {!! 'selected' !!} @endif value="fa-hourglass-half ">hourglass-half </option>
<option @if($selected == "fa-hourglass-o" ) {!! 'selected' !!} @endif value="fa-hourglass-o ">hourglass-o </option>
<option @if($selected == "fa-hourglass-start" ) {!! 'selected' !!} @endif value="fa-hourglass-start ">hourglass-start </option>
<option @if($selected == "fa-houzz" ) {!! 'selected' !!} @endif value="fa-houzz ">houzz </option>
<option @if($selected == "fa-html5" ) {!! 'selected' !!} @endif value="fa-html5 ">html5 </option>
<option @if($selected == "fa-i-cursor" ) {!! 'selected' !!} @endif value="fa-i-cursor ">i-cursor </option>
<option @if($selected == "fa-ils" ) {!! 'selected' !!} @endif value="fa-ils ">ils </option>
<option @if($selected == "fa-imageEvent" ) {!! 'selected' !!} @endif value="fa-imageEvent ">imageEvent </option>
<option @if($selected == "fa-inbox" ) {!! 'selected' !!} @endif value="fa-inbox ">inbox </option>
<option @if($selected == "fa-indent" ) {!! 'selected' !!} @endif value="fa-indent ">indent </option>
<option @if($selected == "fa-industry" ) {!! 'selected' !!} @endif value="fa-industry ">industry </option>
<option @if($selected == "fa-info" ) {!! 'selected' !!} @endif value="fa-info ">info </option>
<option @if($selected == "fa-info-circle" ) {!! 'selected' !!} @endif value="fa-info-circle ">info-circle </option>
<option @if($selected == "fa-inr" ) {!! 'selected' !!} @endif value="fa-inr ">inr </option>
<option @if($selected == "fa-instagram" ) {!! 'selected' !!} @endif value="fa-instagram ">instagram </option>
<option @if($selected == "fa-institutionEvent" ) {!! 'selected' !!} @endif value="fa-institutionEvent ">institutionEvent </option>
<option @if($selected == "fa-internet-explorer" ) {!! 'selected' !!} @endif value="fa-internet-explorer ">internet-explorer </option>
<option @if($selected == "fa-intersexEvent" ) {!! 'selected' !!} @endif value="fa-intersexEvent ">intersexEvent </option>
<option @if($selected == "fa-ioxhost" ) {!! 'selected' !!} @endif value="fa-ioxhost ">ioxhost </option>
<option @if($selected == "fa-italic" ) {!! 'selected' !!} @endif value="fa-italic ">italic </option>
<option @if($selected == "fa-joomla" ) {!! 'selected' !!} @endif value="fa-joomla ">joomla </option>
<option @if($selected == "fa-jpy" ) {!! 'selected' !!} @endif value="fa-jpy ">jpy </option>
<option @if($selected == "fa-jsfiddle" ) {!! 'selected' !!} @endif value="fa-jsfiddle ">jsfiddle </option>
<option @if($selected == "fa-key" ) {!! 'selected' !!} @endif value="fa-key ">key </option>
<option @if($selected == "fa-keyboard-o" ) {!! 'selected' !!} @endif value="fa-keyboard-o ">keyboard-o </option>
<option @if($selected == "fa-krw" ) {!! 'selected' !!} @endif value="fa-krw ">krw </option>
<option @if($selected == "fa-language" ) {!! 'selected' !!} @endif value="fa-language ">language </option>
<option @if($selected == "fa-laptop" ) {!! 'selected' !!} @endif value="fa-laptop ">laptop </option>
<option @if($selected == "fa-lastfm" ) {!! 'selected' !!} @endif value="fa-lastfm ">lastfm </option>
<option @if($selected == "fa-lastfm-square" ) {!! 'selected' !!} @endif value="fa-lastfm-square ">lastfm-square </option>
<option @if($selected == "fa-leaf" ) {!! 'selected' !!} @endif value="fa-leaf ">leaf </option>
<option @if($selected == "fa-leanpub" ) {!! 'selected' !!} @endif value="fa-leanpub ">leanpub </option>
<option @if($selected == "fa-legalEvent" ) {!! 'selected' !!} @endif value="fa-legalEvent ">legalEvent </option>
<option @if($selected == "fa-lemon-o" ) {!! 'selected' !!} @endif value="fa-lemon-o ">lemon-o </option>
<option @if($selected == "fa-level-down" ) {!! 'selected' !!} @endif value="fa-level-down ">level-down </option>
<option @if($selected == "fa-level-up" ) {!! 'selected' !!} @endif value="fa-level-up ">level-up </option>
<option @if($selected == "fa-life-bouyEvent" ) {!! 'selected' !!} @endif value="fa-life-bouyEvent ">life-bouyEvent </option>
<option @if($selected == "fa-life-buoyEvent" ) {!! 'selected' !!} @endif value="fa-life-buoyEvent ">life-buoyEvent </option>
<option @if($selected == "fa-life-ring" ) {!! 'selected' !!} @endif value="fa-life-ring ">life-ring </option>
<option @if($selected == "fa-life-saverEvent" ) {!! 'selected' !!} @endif value="fa-life-saverEvent ">life-saverEvent </option>
<option @if($selected == "fa-lightbulb-o" ) {!! 'selected' !!} @endif value="fa-lightbulb-o ">lightbulb-o </option>
<option @if($selected == "fa-line-chart" ) {!! 'selected' !!} @endif value="fa-line-chart ">line-chart </option>
<option @if($selected == "fa-link" ) {!! 'selected' !!} @endif value="fa-link ">link </option>
<option @if($selected == "fa-linkedin" ) {!! 'selected' !!} @endif value="fa-linkedin ">linkedin </option>
<option @if($selected == "fa-linkedin-square" ) {!! 'selected' !!} @endif value="fa-linkedin-square ">linkedin-square </option>
<option @if($selected == "fa-linux" ) {!! 'selected' !!} @endif value="fa-linux ">linux </option>
<option @if($selected == "fa-list" ) {!! 'selected' !!} @endif value="fa-list ">list </option>
<option @if($selected == "fa-list-alt" ) {!! 'selected' !!} @endif value="fa-list-alt ">list-alt </option>
<option @if($selected == "fa-list-ol" ) {!! 'selected' !!} @endif value="fa-list-ol ">list-ol </option>
<option @if($selected == "fa-list-ul" ) {!! 'selected' !!} @endif value="fa-list-ul ">list-ul </option>
<option @if($selected == "fa-location-arrow" ) {!! 'selected' !!} @endif value="fa-location-arrow ">location-arrow </option>
<option @if($selected == "fa-lock" ) {!! 'selected' !!} @endif value="fa-lock ">lock </option>
<option @if($selected == "fa-long-arrow-down" ) {!! 'selected' !!} @endif value="fa-long-arrow-down ">long-arrow-down </option>
<option @if($selected == "fa-long-arrow-left" ) {!! 'selected' !!} @endif value="fa-long-arrow-left ">long-arrow-left </option>
<option @if($selected == "fa-long-arrow-right" ) {!! 'selected' !!} @endif value="fa-long-arrow-right ">long-arrow-right </option>
<option @if($selected == "fa-long-arrow-up" ) {!! 'selected' !!} @endif value="fa-long-arrow-up ">long-arrow-up </option>
<option @if($selected == "fa-magic" ) {!! 'selected' !!} @endif value="fa-magic ">magic </option>
<option @if($selected == "fa-magnet" ) {!! 'selected' !!} @endif value="fa-magnet ">magnet </option>
<option @if($selected == "fa-mail-forwardEvent" ) {!! 'selected' !!} @endif value="fa-mail-forwardEvent ">mail-forwardEvent </option>
<option @if($selected == "fa-mail-replyEvent" ) {!! 'selected' !!} @endif value="fa-mail-replyEvent ">mail-replyEvent </option>
<option @if($selected == "fa-mail-reply-allEvent" ) {!! 'selected' !!} @endif value="fa-mail-reply-allEvent ">mail-reply-allEvent </option>
<option @if($selected == "fa-male" ) {!! 'selected' !!} @endif value="fa-male ">male </option>
<option @if($selected == "fa-map" ) {!! 'selected' !!} @endif value="fa-map ">map </option>
<option @if($selected == "fa-map-marker" ) {!! 'selected' !!} @endif value="fa-map-marker ">map-marker </option>
<option @if($selected == "fa-map-o" ) {!! 'selected' !!} @endif value="fa-map-o ">map-o </option>
<option @if($selected == "fa-map-pin" ) {!! 'selected' !!} @endif value="fa-map-pin ">map-pin </option>
<option @if($selected == "fa-map-signs" ) {!! 'selected' !!} @endif value="fa-map-signs ">map-signs </option>
<option @if($selected == "fa-mars" ) {!! 'selected' !!} @endif value="fa-mars ">mars </option>
<option @if($selected == "fa-mars-double" ) {!! 'selected' !!} @endif value="fa-mars-double ">mars-double </option>
<option @if($selected == "fa-mars-stroke" ) {!! 'selected' !!} @endif value="fa-mars-stroke ">mars-stroke </option>
<option @if($selected == "fa-mars-stroke-h" ) {!! 'selected' !!} @endif value="fa-mars-stroke-h ">mars-stroke-h </option>
<option @if($selected == "fa-mars-stroke-v" ) {!! 'selected' !!} @endif value="fa-mars-stroke-v ">mars-stroke-v </option>
<option @if($selected == "fa-maxcdn" ) {!! 'selected' !!} @endif value="fa-maxcdn ">maxcdn </option>
<option @if($selected == "fa-meanpath" ) {!! 'selected' !!} @endif value="fa-meanpath ">meanpath </option>
<option @if($selected == "fa-medium" ) {!! 'selected' !!} @endif value="fa-medium ">medium </option>
<option @if($selected == "fa-medkit" ) {!! 'selected' !!} @endif value="fa-medkit ">medkit </option>
<option @if($selected == "fa-meh-o" ) {!! 'selected' !!} @endif value="fa-meh-o ">meh-o </option>
<option @if($selected == "fa-mercury" ) {!! 'selected' !!} @endif value="fa-mercury ">mercury </option>
<option @if($selected == "fa-microphone" ) {!! 'selected' !!} @endif value="fa-microphone ">microphone </option>
<option @if($selected == "fa-microphone-slash" ) {!! 'selected' !!} @endif value="fa-microphone-slash ">microphone-slash </option>
<option @if($selected == "fa-minus" ) {!! 'selected' !!} @endif value="fa-minus ">minus </option>
<option @if($selected == "fa-minus-circle" ) {!! 'selected' !!} @endif value="fa-minus-circle ">minus-circle </option>
<option @if($selected == "fa-minus-square" ) {!! 'selected' !!} @endif value="fa-minus-square ">minus-square </option>
<option @if($selected == "fa-minus-square-o" ) {!! 'selected' !!} @endif value="fa-minus-square-o ">minus-square-o </option>
<option @if($selected == "fa-mixcloud" ) {!! 'selected' !!} @endif value="fa-mixcloud ">mixcloud </option>
<option @if($selected == "fa-mobile" ) {!! 'selected' !!} @endif value="fa-mobile ">mobile </option>
<option @if($selected == "fa-mobile-phoneEvent" ) {!! 'selected' !!} @endif value="fa-mobile-phoneEvent ">mobile-phoneEvent </option>
<option @if($selected == "fa-modx" ) {!! 'selected' !!} @endif value="fa-modx ">modx </option>
<option @if($selected == "fa-money" ) {!! 'selected' !!} @endif value="fa-money ">money </option>
<option @if($selected == "fa-moon-o" ) {!! 'selected' !!} @endif value="fa-moon-o ">moon-o </option>
<option @if($selected == "fa-mortar-boardEvent" ) {!! 'selected' !!} @endif value="fa-mortar-boardEvent ">mortar-boardEvent </option>
<option @if($selected == "fa-motorcycle" ) {!! 'selected' !!} @endif value="fa-motorcycle ">motorcycle </option>
<option @if($selected == "fa-mouse-pointer" ) {!! 'selected' !!} @endif value="fa-mouse-pointer ">mouse-pointer </option>
<option @if($selected == "fa-music" ) {!! 'selected' !!} @endif value="fa-music ">music </option>
<option @if($selected == "fa-naviconEvent" ) {!! 'selected' !!} @endif value="fa-naviconEvent ">naviconEvent </option>
<option @if($selected == "fa-neuter" ) {!! 'selected' !!} @endif value="fa-neuter ">neuter </option>
<option @if($selected == "fa-newspaper-o" ) {!! 'selected' !!} @endif value="fa-newspaper-o ">newspaper-o </option>
<option @if($selected == "fa-object-group" ) {!! 'selected' !!} @endif value="fa-object-group ">object-group </option>
<option @if($selected == "fa-object-ungroup" ) {!! 'selected' !!} @endif value="fa-object-ungroup ">object-ungroup </option>
<option @if($selected == "fa-odnoklassniki" ) {!! 'selected' !!} @endif value="fa-odnoklassniki ">odnoklassniki </option>
<option @if($selected == "fa-odnoklassniki-square" ) {!! 'selected' !!} @endif value="fa-odnoklassniki-square ">odnoklassniki-square </option>
<option @if($selected == "fa-opencart" ) {!! 'selected' !!} @endif value="fa-opencart ">opencart </option>
<option @if($selected == "fa-openid" ) {!! 'selected' !!} @endif value="fa-openid ">openid </option>
<option @if($selected == "fa-opera" ) {!! 'selected' !!} @endif value="fa-opera ">opera </option>
<option @if($selected == "fa-optin-monster" ) {!! 'selected' !!} @endif value="fa-optin-monster ">optin-monster </option>
<option @if($selected == "fa-outdent" ) {!! 'selected' !!} @endif value="fa-outdent ">outdent </option>
<option @if($selected == "fa-pagelines" ) {!! 'selected' !!} @endif value="fa-pagelines ">pagelines </option>
<option @if($selected == "fa-paint-brush" ) {!! 'selected' !!} @endif value="fa-paint-brush ">paint-brush </option>
<option @if($selected == "fa-paper-plane" ) {!! 'selected' !!} @endif value="fa-paper-plane ">paper-plane </option>
<option @if($selected == "fa-paper-plane-o" ) {!! 'selected' !!} @endif value="fa-paper-plane-o ">paper-plane-o </option>
<option @if($selected == "fa-paperclip" ) {!! 'selected' !!} @endif value="fa-paperclip ">paperclip </option>
<option @if($selected == "fa-paragraph" ) {!! 'selected' !!} @endif value="fa-paragraph ">paragraph </option>
<option @if($selected == "fa-pasteEvent" ) {!! 'selected' !!} @endif value="fa-pasteEvent ">pasteEvent </option>
<option @if($selected == "fa-pause" ) {!! 'selected' !!} @endif value="fa-pause ">pause </option>
<option @if($selected == "fa-pause-circle" ) {!! 'selected' !!} @endif value="fa-pause-circle ">pause-circle </option>
<option @if($selected == "fa-pause-circle-o" ) {!! 'selected' !!} @endif value="fa-pause-circle-o ">pause-circle-o </option>
<option @if($selected == "fa-paw" ) {!! 'selected' !!} @endif value="fa-paw ">paw </option>
<option @if($selected == "fa-paypal" ) {!! 'selected' !!} @endif value="fa-paypal ">paypal </option>
<option @if($selected == "fa-pencil" ) {!! 'selected' !!} @endif value="fa-pencil ">pencil </option>
<option @if($selected == "fa-pencil-square" ) {!! 'selected' !!} @endif value="fa-pencil-square ">pencil-square </option>
<option @if($selected == "fa-pencil-square-o" ) {!! 'selected' !!} @endif value="fa-pencil-square-o ">pencil-square-o </option>
<option @if($selected == "fa-percent" ) {!! 'selected' !!} @endif value="fa-percent ">percent </option>
<option @if($selected == "fa-phone" ) {!! 'selected' !!} @endif value="fa-phone ">phone </option>
<option @if($selected == "fa-phone-square" ) {!! 'selected' !!} @endif value="fa-phone-square ">phone-square </option>
<option @if($selected == "fa-photoEvent" ) {!! 'selected' !!} @endif value="fa-photoEvent ">photoEvent </option>
<option @if($selected == "fa-picture-o" ) {!! 'selected' !!} @endif value="fa-picture-o ">picture-o </option>
<option @if($selected == "fa-pie-chart" ) {!! 'selected' !!} @endif value="fa-pie-chart ">pie-chart </option>
<option @if($selected == "fa-pied-piper" ) {!! 'selected' !!} @endif value="fa-pied-piper ">pied-piper </option>
<option @if($selected == "fa-pied-piper-alt" ) {!! 'selected' !!} @endif value="fa-pied-piper-alt ">pied-piper-alt </option>
<option @if($selected == "fa-pinterest" ) {!! 'selected' !!} @endif value="fa-pinterest ">pinterest </option>
<option @if($selected == "fa-pinterest-p" ) {!! 'selected' !!} @endif value="fa-pinterest-p ">pinterest-p </option>
<option @if($selected == "fa-pinterest-square" ) {!! 'selected' !!} @endif value="fa-pinterest-square ">pinterest-square </option>
<option @if($selected == "fa-plane" ) {!! 'selected' !!} @endif value="fa-plane ">plane </option>
<option @if($selected == "fa-play" ) {!! 'selected' !!} @endif value="fa-play ">play </option>
<option @if($selected == "fa-play-circle" ) {!! 'selected' !!} @endif value="fa-play-circle ">play-circle </option>
<option @if($selected == "fa-play-circle-o" ) {!! 'selected' !!} @endif value="fa-play-circle-o ">play-circle-o </option>
<option @if($selected == "fa-plug" ) {!! 'selected' !!} @endif value="fa-plug ">plug </option>
<option @if($selected == "fa-plus" ) {!! 'selected' !!} @endif value="fa-plus ">plus </option>
<option @if($selected == "fa-plus-circle" ) {!! 'selected' !!} @endif value="fa-plus-circle ">plus-circle </option>
<option @if($selected == "fa-plus-square" ) {!! 'selected' !!} @endif value="fa-plus-square ">plus-square </option>
<option @if($selected == "fa-plus-square-o" ) {!! 'selected' !!} @endif value="fa-plus-square-o ">plus-square-o </option>
<option @if($selected == "fa-power-off" ) {!! 'selected' !!} @endif value="fa-power-off ">power-off </option>
<option @if($selected == "fa-print" ) {!! 'selected' !!} @endif value="fa-print ">print </option>
<option @if($selected == "fa-product-hunt" ) {!! 'selected' !!} @endif value="fa-product-hunt ">product-hunt </option>
<option @if($selected == "fa-puzzle-piece" ) {!! 'selected' !!} @endif value="fa-puzzle-piece ">puzzle-piece </option>
<option @if($selected == "fa-qq" ) {!! 'selected' !!} @endif value="fa-qq ">qq </option>
<option @if($selected == "fa-qrcode" ) {!! 'selected' !!} @endif value="fa-qrcode ">qrcode </option>
<option @if($selected == "fa-question" ) {!! 'selected' !!} @endif value="fa-question ">question </option>
<option @if($selected == "fa-question-circle" ) {!! 'selected' !!} @endif value="fa-question-circle ">question-circle </option>
<option @if($selected == "fa-quote-left" ) {!! 'selected' !!} @endif value="fa-quote-left ">quote-left </option>
<option @if($selected == "fa-quote-right" ) {!! 'selected' !!} @endif value="fa-quote-right ">quote-right </option>
<option @if($selected == "fa-raEvent" ) {!! 'selected' !!} @endif value="fa-raEvent ">raEvent </option>
<option @if($selected == "fa-random" ) {!! 'selected' !!} @endif value="fa-random ">random </option>
<option @if($selected == "fa-rebel" ) {!! 'selected' !!} @endif value="fa-rebel ">rebel </option>
<option @if($selected == "fa-recycle" ) {!! 'selected' !!} @endif value="fa-recycle ">recycle </option>
<option @if($selected == "fa-reddit" ) {!! 'selected' !!} @endif value="fa-reddit ">reddit </option>
<option @if($selected == "fa-reddit-alien" ) {!! 'selected' !!} @endif value="fa-reddit-alien ">reddit-alien </option>
<option @if($selected == "fa-reddit-square" ) {!! 'selected' !!} @endif value="fa-reddit-square ">reddit-square </option>
<option @if($selected == "fa-refresh" ) {!! 'selected' !!} @endif value="fa-refresh ">refresh </option>
<option @if($selected == "fa-registered" ) {!! 'selected' !!} @endif value="fa-registered ">registered </option>
<option @if($selected == "fa-removeEvent" ) {!! 'selected' !!} @endif value="fa-removeEvent ">removeEvent </option>
<option @if($selected == "fa-renren" ) {!! 'selected' !!} @endif value="fa-renren ">renren </option>
<option @if($selected == "fa-reorderEvent" ) {!! 'selected' !!} @endif value="fa-reorderEvent ">reorderEvent </option>
<option @if($selected == "fa-repeat" ) {!! 'selected' !!} @endif value="fa-repeat ">repeat </option>
<option @if($selected == "fa-reply" ) {!! 'selected' !!} @endif value="fa-reply ">reply </option>
<option @if($selected == "fa-reply-all" ) {!! 'selected' !!} @endif value="fa-reply-all ">reply-all </option>
<option @if($selected == "fa-retweet" ) {!! 'selected' !!} @endif value="fa-retweet ">retweet </option>
<option @if($selected == "fa-rmbEvent" ) {!! 'selected' !!} @endif value="fa-rmbEvent ">rmbEvent </option>
<option @if($selected == "fa-road" ) {!! 'selected' !!} @endif value="fa-road ">road </option>
<option @if($selected == "fa-rocket" ) {!! 'selected' !!} @endif value="fa-rocket ">rocket </option>
<option @if($selected == "fa-rotate-leftEvent" ) {!! 'selected' !!} @endif value="fa-rotate-leftEvent ">rotate-leftEvent </option>
<option @if($selected == "fa-rotate-rightEvent" ) {!! 'selected' !!} @endif value="fa-rotate-rightEvent ">rotate-rightEvent </option>
<option @if($selected == "fa-roubleEvent" ) {!! 'selected' !!} @endif value="fa-roubleEvent ">roubleEvent </option>
<option @if($selected == "fa-rss" ) {!! 'selected' !!} @endif value="fa-rss ">rss </option>
<option @if($selected == "fa-rss-square" ) {!! 'selected' !!} @endif value="fa-rss-square ">rss-square </option>
<option @if($selected == "fa-rub" ) {!! 'selected' !!} @endif value="fa-rub ">rub </option>
<option @if($selected == "fa-rubleEvent" ) {!! 'selected' !!} @endif value="fa-rubleEvent ">rubleEvent </option>
<option @if($selected == "fa-rupeeEvent" ) {!! 'selected' !!} @endif value="fa-rupeeEvent ">rupeeEvent </option>
<option @if($selected == "fa-safari" ) {!! 'selected' !!} @endif value="fa-safari ">safari </option>
<option @if($selected == "fa-saveEvent" ) {!! 'selected' !!} @endif value="fa-saveEvent ">saveEvent </option>
<option @if($selected == "fa-scissors" ) {!! 'selected' !!} @endif value="fa-scissors ">scissors </option>
<option @if($selected == "fa-scribd" ) {!! 'selected' !!} @endif value="fa-scribd ">scribd </option>
<option @if($selected == "fa-search" ) {!! 'selected' !!} @endif value="fa-search ">search </option>
<option @if($selected == "fa-search-minus" ) {!! 'selected' !!} @endif value="fa-search-minus ">search-minus </option>
<option @if($selected == "fa-search-plus" ) {!! 'selected' !!} @endif value="fa-search-plus ">search-plus </option>
<option @if($selected == "fa-sellsy" ) {!! 'selected' !!} @endif value="fa-sellsy ">sellsy </option>
<option @if($selected == "fa-sendEvent" ) {!! 'selected' !!} @endif value="fa-sendEvent ">sendEvent </option>
<option @if($selected == "fa-send-oEvent" ) {!! 'selected' !!} @endif value="fa-send-oEvent ">send-oEvent </option>
<option @if($selected == "fa-server" ) {!! 'selected' !!} @endif value="fa-server ">server </option>
<option @if($selected == "fa-share" ) {!! 'selected' !!} @endif value="fa-share ">share </option>
<option @if($selected == "fa-share-alt" ) {!! 'selected' !!} @endif value="fa-share-alt ">share-alt </option>
<option @if($selected == "fa-share-alt-square" ) {!! 'selected' !!} @endif value="fa-share-alt-square ">share-alt-square </option>
<option @if($selected == "fa-share-square" ) {!! 'selected' !!} @endif value="fa-share-square ">share-square </option>
<option @if($selected == "fa-share-square-o" ) {!! 'selected' !!} @endif value="fa-share-square-o ">share-square-o </option>
<option @if($selected == "fa-shekelEvent" ) {!! 'selected' !!} @endif value="fa-shekelEvent ">shekelEvent </option>
<option @if($selected == "fa-sheqelEvent" ) {!! 'selected' !!} @endif value="fa-sheqelEvent ">sheqelEvent </option>
<option @if($selected == "fa-shield" ) {!! 'selected' !!} @endif value="fa-shield ">shield </option>
<option @if($selected == "fa-ship" ) {!! 'selected' !!} @endif value="fa-ship ">ship </option>
<option @if($selected == "fa-shirtsinbulk" ) {!! 'selected' !!} @endif value="fa-shirtsinbulk ">shirtsinbulk </option>
<option @if($selected == "fa-shopping-bag" ) {!! 'selected' !!} @endif value="fa-shopping-bag ">shopping-bag </option>
<option @if($selected == "fa-shopping-basket" ) {!! 'selected' !!} @endif value="fa-shopping-basket ">shopping-basket </option>
<option @if($selected == "fa-shopping-cart" ) {!! 'selected' !!} @endif value="fa-shopping-cart ">shopping-cart </option>
<option @if($selected == "fa-sign-in" ) {!! 'selected' !!} @endif value="fa-sign-in ">sign-in </option>
<option @if($selected == "fa-sign-out" ) {!! 'selected' !!} @endif value="fa-sign-out ">sign-out </option>
<option @if($selected == "fa-signal" ) {!! 'selected' !!} @endif value="fa-signal ">signal </option>
<option @if($selected == "fa-simplybuilt" ) {!! 'selected' !!} @endif value="fa-simplybuilt ">simplybuilt </option>
<option @if($selected == "fa-sitemap" ) {!! 'selected' !!} @endif value="fa-sitemap ">sitemap </option>
<option @if($selected == "fa-skyatlas" ) {!! 'selected' !!} @endif value="fa-skyatlas ">skyatlas </option>
<option @if($selected == "fa-skype" ) {!! 'selected' !!} @endif value="fa-skype ">skype </option>
<option @if($selected == "fa-slack" ) {!! 'selected' !!} @endif value="fa-slack ">slack </option>
<option @if($selected == "fa-sliders" ) {!! 'selected' !!} @endif value="fa-sliders ">sliders </option>
<option @if($selected == "fa-slideshare" ) {!! 'selected' !!} @endif value="fa-slideshare ">slideshare </option>
<option @if($selected == "fa-smile-o" ) {!! 'selected' !!} @endif value="fa-smile-o ">smile-o </option>
<option @if($selected == "fa-soccer-ball-oEvent" ) {!! 'selected' !!} @endif value="fa-soccer-ball-oEvent ">soccer-ball-oEvent </option>
<option @if($selected == "fa-sort" ) {!! 'selected' !!} @endif value="fa-sort ">sort </option>
<option @if($selected == "fa-sort-alpha-asc" ) {!! 'selected' !!} @endif value="fa-sort-alpha-asc ">sort-alpha-asc </option>
<option @if($selected == "fa-sort-alpha-desc" ) {!! 'selected' !!} @endif value="fa-sort-alpha-desc ">sort-alpha-desc </option>
<option @if($selected == "fa-sort-amount-asc" ) {!! 'selected' !!} @endif value="fa-sort-amount-asc ">sort-amount-asc </option>
<option @if($selected == "fa-sort-amount-desc" ) {!! 'selected' !!} @endif value="fa-sort-amount-desc ">sort-amount-desc </option>
<option @if($selected == "fa-sort-asc" ) {!! 'selected' !!} @endif value="fa-sort-asc ">sort-asc </option>
<option @if($selected == "fa-sort-desc" ) {!! 'selected' !!} @endif value="fa-sort-desc ">sort-desc </option>
<option @if($selected == "fa-sort-downEvent" ) {!! 'selected' !!} @endif value="fa-sort-downEvent ">sort-downEvent </option>
<option @if($selected == "fa-sort-numeric-asc" ) {!! 'selected' !!} @endif value="fa-sort-numeric-asc ">sort-numeric-asc </option>
<option @if($selected == "fa-sort-numeric-desc" ) {!! 'selected' !!} @endif value="fa-sort-numeric-desc ">sort-numeric-desc </option>
<option @if($selected == "fa-sort-upEvent" ) {!! 'selected' !!} @endif value="fa-sort-upEvent ">sort-upEvent </option>
<option @if($selected == "fa-soundcloud" ) {!! 'selected' !!} @endif value="fa-soundcloud ">soundcloud </option>
<option @if($selected == "fa-space-shuttle" ) {!! 'selected' !!} @endif value="fa-space-shuttle ">space-shuttle </option>
<option @if($selected == "fa-spinner" ) {!! 'selected' !!} @endif value="fa-spinner ">spinner </option>
<option @if($selected == "fa-spoon" ) {!! 'selected' !!} @endif value="fa-spoon ">spoon </option>
<option @if($selected == "fa-spotify" ) {!! 'selected' !!} @endif value="fa-spotify ">spotify </option>
<option @if($selected == "fa-square" ) {!! 'selected' !!} @endif value="fa-square ">square </option>
<option @if($selected == "fa-square-o" ) {!! 'selected' !!} @endif value="fa-square-o ">square-o </option>
<option @if($selected == "fa-stack-exchange" ) {!! 'selected' !!} @endif value="fa-stack-exchange ">stack-exchange </option>
<option @if($selected == "fa-stack-overflow" ) {!! 'selected' !!} @endif value="fa-stack-overflow ">stack-overflow </option>
<option @if($selected == "fa-star" ) {!! 'selected' !!} @endif value="fa-star ">star </option>
<option @if($selected == "fa-star-half" ) {!! 'selected' !!} @endif value="fa-star-half ">star-half </option>
<option @if($selected == "fa-star-half-emptyEvent" ) {!! 'selected' !!} @endif value="fa-star-half-emptyEvent ">star-half-emptyEvent </option>
<option @if($selected == "fa-star-half-fullEvent" ) {!! 'selected' !!} @endif value="fa-star-half-fullEvent ">star-half-fullEvent </option>
<option @if($selected == "fa-star-half-o" ) {!! 'selected' !!} @endif value="fa-star-half-o ">star-half-o </option>
<option @if($selected == "fa-star-o" ) {!! 'selected' !!} @endif value="fa-star-o ">star-o </option>
<option @if($selected == "fa-steam" ) {!! 'selected' !!} @endif value="fa-steam ">steam </option>
<option @if($selected == "fa-steam-square" ) {!! 'selected' !!} @endif value="fa-steam-square ">steam-square </option>
<option @if($selected == "fa-step-backward" ) {!! 'selected' !!} @endif value="fa-step-backward ">step-backward </option>
<option @if($selected == "fa-step-forward" ) {!! 'selected' !!} @endif value="fa-step-forward ">step-forward </option>
<option @if($selected == "fa-stethoscope" ) {!! 'selected' !!} @endif value="fa-stethoscope ">stethoscope </option>
<option @if($selected == "fa-sticky-note" ) {!! 'selected' !!} @endif value="fa-sticky-note ">sticky-note </option>
<option @if($selected == "fa-sticky-note-o" ) {!! 'selected' !!} @endif value="fa-sticky-note-o ">sticky-note-o </option>
<option @if($selected == "fa-stop" ) {!! 'selected' !!} @endif value="fa-stop ">stop </option>
<option @if($selected == "fa-stop-circle" ) {!! 'selected' !!} @endif value="fa-stop-circle ">stop-circle </option>
<option @if($selected == "fa-stop-circle-o" ) {!! 'selected' !!} @endif value="fa-stop-circle-o ">stop-circle-o </option>
<option @if($selected == "fa-street-view" ) {!! 'selected' !!} @endif value="fa-street-view ">street-view </option>
<option @if($selected == "fa-strikethrough" ) {!! 'selected' !!} @endif value="fa-strikethrough ">strikethrough </option>
<option @if($selected == "fa-stumbleupon" ) {!! 'selected' !!} @endif value="fa-stumbleupon ">stumbleupon </option>
<option @if($selected == "fa-stumbleupon-circle" ) {!! 'selected' !!} @endif value="fa-stumbleupon-circle ">stumbleupon-circle </option>
<option @if($selected == "fa-subscript" ) {!! 'selected' !!} @endif value="fa-subscript ">subscript </option>
<option @if($selected == "fa-subway" ) {!! 'selected' !!} @endif value="fa-subway ">subway </option>
<option @if($selected == "fa-suitcase" ) {!! 'selected' !!} @endif value="fa-suitcase ">suitcase </option>
<option @if($selected == "fa-sun-o" ) {!! 'selected' !!} @endif value="fa-sun-o ">sun-o </option>
<option @if($selected == "fa-superscript" ) {!! 'selected' !!} @endif value="fa-superscript ">superscript </option>
<option @if($selected == "fa-supportEvent" ) {!! 'selected' !!} @endif value="fa-supportEvent ">supportEvent </option>
<option @if($selected == "fa-table" ) {!! 'selected' !!} @endif value="fa-table ">table </option>
<option @if($selected == "fa-tablet" ) {!! 'selected' !!} @endif value="fa-tablet ">tablet </option>
<option @if($selected == "fa-tachometer" ) {!! 'selected' !!} @endif value="fa-tachometer ">tachometer </option>
<option @if($selected == "fa-tag" ) {!! 'selected' !!} @endif value="fa-tag ">tag </option>
<option @if($selected == "fa-tags" ) {!! 'selected' !!} @endif value="fa-tags ">tags </option>
<option @if($selected == "fa-tasks" ) {!! 'selected' !!} @endif value="fa-tasks ">tasks </option>
<option @if($selected == "fa-taxi" ) {!! 'selected' !!} @endif value="fa-taxi ">taxi </option>
<option @if($selected == "fa-television" ) {!! 'selected' !!} @endif value="fa-television ">television </option>
<option @if($selected == "fa-tencent-weibo" ) {!! 'selected' !!} @endif value="fa-tencent-weibo ">tencent-weibo </option>
<option @if($selected == "fa-terminal" ) {!! 'selected' !!} @endif value="fa-terminal ">terminal </option>
<option @if($selected == "fa-text-height" ) {!! 'selected' !!} @endif value="fa-text-height ">text-height </option>
<option @if($selected == "fa-text-width" ) {!! 'selected' !!} @endif value="fa-text-width ">text-width </option>
<option @if($selected == "fa-th" ) {!! 'selected' !!} @endif value="fa-th ">th </option>
<option @if($selected == "fa-th-large" ) {!! 'selected' !!} @endif value="fa-th-large ">th-large </option>
<option @if($selected == "fa-th-list" ) {!! 'selected' !!} @endif value="fa-th-list ">th-list </option>
<option @if($selected == "fa-thumb-tack" ) {!! 'selected' !!} @endif value="fa-thumb-tack ">thumb-tack </option>
<option @if($selected == "fa-thumbs-down" ) {!! 'selected' !!} @endif value="fa-thumbs-down ">thumbs-down </option>
<option @if($selected == "fa-thumbs-o-down" ) {!! 'selected' !!} @endif value="fa-thumbs-o-down ">thumbs-o-down </option>
<option @if($selected == "fa-thumbs-o-up" ) {!! 'selected' !!} @endif value="fa-thumbs-o-up ">thumbs-o-up </option>
<option @if($selected == "fa-thumbs-up" ) {!! 'selected' !!} @endif value="fa-thumbs-up ">thumbs-up </option>
<option @if($selected == "fa-ticket" ) {!! 'selected' !!} @endif value="fa-ticket ">ticket </option>
<option @if($selected == "fa-times" ) {!! 'selected' !!} @endif value="fa-times ">times </option>
<option @if($selected == "fa-times-circle" ) {!! 'selected' !!} @endif value="fa-times-circle ">times-circle </option>
<option @if($selected == "fa-times-circle-o" ) {!! 'selected' !!} @endif value="fa-times-circle-o ">times-circle-o </option>
<option @if($selected == "fa-tint" ) {!! 'selected' !!} @endif value="fa-tint ">tint </option>
<option @if($selected == "fa-toggle-downEvent" ) {!! 'selected' !!} @endif value="fa-toggle-downEvent ">toggle-downEvent </option>
<option @if($selected == "fa-toggle-leftEvent" ) {!! 'selected' !!} @endif value="fa-toggle-leftEvent ">toggle-leftEvent </option>
<option @if($selected == "fa-toggle-off" ) {!! 'selected' !!} @endif value="fa-toggle-off ">toggle-off </option>
<option @if($selected == "fa-toggle-on" ) {!! 'selected' !!} @endif value="fa-toggle-on ">toggle-on </option>
<option @if($selected == "fa-toggle-rightEvent" ) {!! 'selected' !!} @endif value="fa-toggle-rightEvent ">toggle-rightEvent </option>
<option @if($selected == "fa-toggle-upEvent" ) {!! 'selected' !!} @endif value="fa-toggle-upEvent ">toggle-upEvent </option>
<option @if($selected == "fa-trademark" ) {!! 'selected' !!} @endif value="fa-trademark ">trademark </option>
<option @if($selected == "fa-train" ) {!! 'selected' !!} @endif value="fa-train ">train </option>
<option @if($selected == "fa-transgender" ) {!! 'selected' !!} @endif value="fa-transgender ">transgender </option>
<option @if($selected == "fa-transgender-alt" ) {!! 'selected' !!} @endif value="fa-transgender-alt ">transgender-alt </option>
<option @if($selected == "fa-trash" ) {!! 'selected' !!} @endif value="fa-trash ">trash </option>
<option @if($selected == "fa-trash-o" ) {!! 'selected' !!} @endif value="fa-trash-o ">trash-o </option>
<option @if($selected == "fa-tree" ) {!! 'selected' !!} @endif value="fa-tree ">tree </option>
<option @if($selected == "fa-trello" ) {!! 'selected' !!} @endif value="fa-trello ">trello </option>
<option @if($selected == "fa-tripadvisor" ) {!! 'selected' !!} @endif value="fa-tripadvisor ">tripadvisor </option>
<option @if($selected == "fa-trophy" ) {!! 'selected' !!} @endif value="fa-trophy ">trophy </option>
<option @if($selected == "fa-truck" ) {!! 'selected' !!} @endif value="fa-truck ">truck </option>
<option @if($selected == "fa-try" ) {!! 'selected' !!} @endif value="fa-try ">try </option>
<option @if($selected == "fa-tty" ) {!! 'selected' !!} @endif value="fa-tty ">tty </option>
<option @if($selected == "fa-tumblr" ) {!! 'selected' !!} @endif value="fa-tumblr ">tumblr </option>
<option @if($selected == "fa-tumblr-square" ) {!! 'selected' !!} @endif value="fa-tumblr-square ">tumblr-square </option>
<option @if($selected == "fa-turkish-liraEvent" ) {!! 'selected' !!} @endif value="fa-turkish-liraEvent ">turkish-liraEvent </option>
<option @if($selected == "fa-tvEvent" ) {!! 'selected' !!} @endif value="fa-tvEvent ">tvEvent </option>
<option @if($selected == "fa-twitch" ) {!! 'selected' !!} @endif value="fa-twitch ">twitch </option>
<option @if($selected == "fa-twitter" ) {!! 'selected' !!} @endif value="fa-twitter ">twitter </option>
<option @if($selected == "fa-twitter-square" ) {!! 'selected' !!} @endif value="fa-twitter-square ">twitter-square </option>
<option @if($selected == "fa-umbrella" ) {!! 'selected' !!} @endif value="fa-umbrella ">umbrella </option>
<option @if($selected == "fa-underline" ) {!! 'selected' !!} @endif value="fa-underline ">underline </option>
<option @if($selected == "fa-undo" ) {!! 'selected' !!} @endif value="fa-undo ">undo </option>
<option @if($selected == "fa-university" ) {!! 'selected' !!} @endif value="fa-university ">university </option>
<option @if($selected == "fa-unlinkEvent" ) {!! 'selected' !!} @endif value="fa-unlinkEvent ">unlinkEvent </option>
<option @if($selected == "fa-unlock" ) {!! 'selected' !!} @endif value="fa-unlock ">unlock </option>
<option @if($selected == "fa-unlock-alt" ) {!! 'selected' !!} @endif value="fa-unlock-alt ">unlock-alt </option>
<option @if($selected == "fa-unsortedEvent" ) {!! 'selected' !!} @endif value="fa-unsortedEvent ">unsortedEvent </option>
<option @if($selected == "fa-upload" ) {!! 'selected' !!} @endif value="fa-upload ">upload </option>
<option @if($selected == "fa-usb" ) {!! 'selected' !!} @endif value="fa-usb ">usb </option>
<option @if($selected == "fa-usd" ) {!! 'selected' !!} @endif value="fa-usd ">usd </option>
<option @if($selected == "fa-user" ) {!! 'selected' !!} @endif value="fa-user ">user </option>
<option @if($selected == "fa-user-md" ) {!! 'selected' !!} @endif value="fa-user-md ">user-md </option>
<option @if($selected == "fa-user-plus" ) {!! 'selected' !!} @endif value="fa-user-plus ">user-plus </option>
<option @if($selected == "fa-user-secret" ) {!! 'selected' !!} @endif value="fa-user-secret ">user-secret </option>
<option @if($selected == "fa-user-times" ) {!! 'selected' !!} @endif value="fa-user-times ">user-times </option>
<option @if($selected == "fa-users" ) {!! 'selected' !!} @endif value="fa-users ">users </option>
<option @if($selected == "fa-venus" ) {!! 'selected' !!} @endif value="fa-venus ">venus </option>
<option @if($selected == "fa-venus-double" ) {!! 'selected' !!} @endif value="fa-venus-double ">venus-double </option>
<option @if($selected == "fa-venus-mars" ) {!! 'selected' !!} @endif value="fa-venus-mars ">venus-mars </option>
<option @if($selected == "fa-viacoin" ) {!! 'selected' !!} @endif value="fa-viacoin ">viacoin </option>
<option @if($selected == "fa-video-camera" ) {!! 'selected' !!} @endif value="fa-video-camera ">video-camera </option>
<option @if($selected == "fa-vimeo" ) {!! 'selected' !!} @endif value="fa-vimeo ">vimeo </option>
<option @if($selected == "fa-vimeo-square" ) {!! 'selected' !!} @endif value="fa-vimeo-square ">vimeo-square </option>
<option @if($selected == "fa-vine" ) {!! 'selected' !!} @endif value="fa-vine ">vine </option>
<option @if($selected == "fa-vk" ) {!! 'selected' !!} @endif value="fa-vk ">vk </option>
<option @if($selected == "fa-volume-down" ) {!! 'selected' !!} @endif value="fa-volume-down ">volume-down </option>
<option @if($selected == "fa-volume-off" ) {!! 'selected' !!} @endif value="fa-volume-off ">volume-off </option>
<option @if($selected == "fa-volume-up" ) {!! 'selected' !!} @endif value="fa-volume-up ">volume-up </option>
<option @if($selected == "fa-warningEvent" ) {!! 'selected' !!} @endif value="fa-warningEvent ">warningEvent </option>
<option @if($selected == "fa-wechatEvent" ) {!! 'selected' !!} @endif value="fa-wechatEvent ">wechatEvent </option>
<option @if($selected == "fa-weibo" ) {!! 'selected' !!} @endif value="fa-weibo ">weibo </option>
<option @if($selected == "fa-weixin" ) {!! 'selected' !!} @endif value="fa-weixin ">weixin </option>
<option @if($selected == "fa-whatsapp" ) {!! 'selected' !!} @endif value="fa-whatsapp ">whatsapp </option>
<option @if($selected == "fa-wheelchair" ) {!! 'selected' !!} @endif value="fa-wheelchair ">wheelchair </option>
<option @if($selected == "fa-wifi" ) {!! 'selected' !!} @endif value="fa-wifi ">wifi </option>
<option @if($selected == "fa-wikipedia-w" ) {!! 'selected' !!} @endif value="fa-wikipedia-w ">wikipedia-w </option>
<option @if($selected == "fa-windows" ) {!! 'selected' !!} @endif value="fa-windows ">windows </option>
<option @if($selected == "fa-wonEvent" ) {!! 'selected' !!} @endif value="fa-wonEvent ">wonEvent </option>
<option @if($selected == "fa-wordpress" ) {!! 'selected' !!} @endif value="fa-wordpress ">wordpress </option>
<option @if($selected == "fa-wrench" ) {!! 'selected' !!} @endif value="fa-wrench ">wrench </option>
<option @if($selected == "fa-xing" ) {!! 'selected' !!} @endif value="fa-xing ">xing </option>
<option @if($selected == "fa-xing-square" ) {!! 'selected' !!} @endif value="fa-xing-square ">xing-square </option>
<option @if($selected == "fa-y-combinator" ) {!! 'selected' !!} @endif value="fa-y-combinator ">y-combinator </option>
<option @if($selected == "fa-y-combinator-squareEvent" ) {!! 'selected' !!} @endif value="fa-y-combinator-squareEvent ">y-combinator-squareEvent </option>
<option @if($selected == "fa-yahoo" ) {!! 'selected' !!} @endif value="fa-yahoo ">yahoo </option>
<option @if($selected == "fa-ycEvent" ) {!! 'selected' !!} @endif value="fa-ycEvent ">ycEvent </option>
<option @if($selected == "fa-yc-squareEvent" ) {!! 'selected' !!} @endif value="fa-yc-squareEvent ">yc-squareEvent </option>
<option @if($selected == "fa-yelp" ) {!! 'selected' !!} @endif value="fa-yelp ">yelp </option>
<option @if($selected == "fa-yenEvent" ) {!! 'selected' !!} @endif value="fa-yenEvent ">yenEvent </option>
<option @if($selected == "fa-youtube" ) {!! 'selected' !!} @endif value="fa-youtube ">youtube </option>
<option @if($selected == "fa-youtube-play" ) {!! 'selected' !!} @endif value="fa-youtube-play ">youtube-play </option>
<option @if($selected == "fa-youtube-square" ) {!! 'selected' !!} @endif value="fa-youtube-square ">youtube-square </option>